[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"
solc_version = "0.8.28"

[rpc_endpoints]
testnet = "https://testnet-rpc.monad.xyz"
mainnet = "https://rpc.monad.xyz"

[etherscan]
testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet-explorer.monad.xyz/api" }
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.monad.xyz/api" }
